#!/bin/bash

FILEIN="${1}"

sed -i 's/county_name=Alameda/county=06001/' ${FILEIN}
sed -i 's/county_name=Alpine/county=06003/' ${FILEIN}
sed -i 's/county_name=Amador/county=06005/' ${FILEIN}
sed -i 's/county_name=Butte/county=06007/' ${FILEIN}
sed -i 's/county_name=Calaveras/county=06009/' ${FILEIN}
sed -i 's/county_name=Colusa/county=06011/' ${FILEIN}
sed -i 's/county_name=Contra+Costa/county=06013/' ${FILEIN}
sed -i 's/county_name=Del+Norte/county=06015/' ${FILEIN}
sed -i 's/county_name=El+Dorado/county=06017/' ${FILEIN}
sed -i 's/county_name=Fresno/county=06019/' ${FILEIN}
sed -i 's/county_name=Glenn/county=06021/' ${FILEIN}
sed -i 's/county_name=Humboldt/county=06023/' ${FILEIN}
sed -i 's/county_name=Imperial/county=06025/' ${FILEIN}
sed -i 's/county_name=Inyo/county=06027/' ${FILEIN}
sed -i 's/county_name=Kern/county=06029/' ${FILEIN}
sed -i 's/county_name=Kings/county=06031/' ${FILEIN}
sed -i 's/county_name=Lake/county=06033/' ${FILEIN}
sed -i 's/county_name=Lassen/county=06035/' ${FILEIN}
sed -i 's/county_name=Los+Angeles/county=06037/' ${FILEIN}
sed -i 's/county_name=Madera/county=06039/' ${FILEIN}
sed -i 's/county_name=Marin/county=06041/' ${FILEIN}
sed -i 's/county_name=Mariposa/county=06043/' ${FILEIN}
sed -i 's/county_name=Mendocino/county=06045/' ${FILEIN}
sed -i 's/county_name=Merced/county=06047/' ${FILEIN}
sed -i 's/county_name=Modoc/county=06049/' ${FILEIN}
sed -i 's/county_name=Mono/county=06051/' ${FILEIN}
sed -i 's/county_name=Monterey/county=06053/' ${FILEIN}
sed -i 's/county_name=Napa/county=06055/' ${FILEIN}
sed -i 's/county_name=Nevada/county=06057/' ${FILEIN}
sed -i 's/county_name=Orange/county=06059/' ${FILEIN}
sed -i 's/county_name=Placer/county=06061/' ${FILEIN}
sed -i 's/county_name=Plumas/county=06063/' ${FILEIN}
sed -i 's/county_name=Riverside/county=06065/' ${FILEIN}
sed -i 's/county_name=Sacramento/county=06067/' ${FILEIN}
sed -i 's/county_name=San+Benito/county=06069/' ${FILEIN}
sed -i 's/county_name=San+Bernardino/county=06071/' ${FILEIN}
sed -i 's/county_name=San+Diego/county=06073/' ${FILEIN}
sed -i 's/county_name=San+Francisco/county=06075/' ${FILEIN}
sed -i 's/county_name=San+Joaquin/county=06077/' ${FILEIN}
sed -i 's/county_name=San+Luis+Obispo/county=06079/' ${FILEIN}
sed -i 's/county_name=San+Mateo/county=06081/' ${FILEIN}
sed -i 's/county_name=Santa+Barbara/county=06083/' ${FILEIN}
sed -i 's/county_name=Santa+Clara/county=06085/' ${FILEIN}
sed -i 's/county_name=Santa+Cruz/county=06087/' ${FILEIN}
sed -i 's/county_name=Shasta/county=06089/' ${FILEIN}
sed -i 's/county_name=Sierra/county=06091/' ${FILEIN}
sed -i 's/county_name=Siskiyou/county=06093/' ${FILEIN}
sed -i 's/county_name=Solano/county=06095/' ${FILEIN}
sed -i 's/county_name=Sonoma/county=06097/' ${FILEIN}
sed -i 's/county_name=Stanislaus/county=06099/' ${FILEIN}
sed -i 's/county_name=Sutter/county=06101/' ${FILEIN}
sed -i 's/county_name=Tehama/county=06103/' ${FILEIN}
sed -i 's/county_name=Trinity/county=06105/' ${FILEIN}
sed -i 's/county_name=Tulare/county=06107/' ${FILEIN}
sed -i 's/county_name=Tuolumne/county=06109/' ${FILEIN}
sed -i 's/county_name=Ventura/county=06111/' ${FILEIN}
sed -i 's/county_name=Yolo/county=06113/' ${FILEIN}
sed -i 's/county_name=Yuba/county=06115/' ${FILEIN}
